# Generated by Django 3.1.3 on 2020-11-13 07:33

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Chrisan Dantes", email="dsadasd@a.c", document = "ddsadsad", phone="3421").save
class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
